my_app/urls.py
from django.urls import path
from my_app.views import *


urlpatterns = [
	path('building/create/', BuildingCreateView.as_view(), name = 'building-create'),
	path('building/list/', BuildingListView.as_view(), name = 'building-list'),
	path('building/detail/<int:pk>/', BuildingDetailView.as_view(), name = 'building-detail'),
	path('building/update/<int:pk>/', BuildingUpdateView.as_view(), name = 'building-update'),
	path('building/delete/<int:pk>/', BuildingDeleteView.as_view(), name = 'building-delete'),
	path('transaction/create', TransactionCreateView.as_view(), name = 'transaction-create'),
	path('transaction/list', TransactionListView.as_view(), name = 'transaction-list'),
	path('transaction/update/<int:pk>/', TransactionUpdateView.as_view(), name = 'transaction-update'),
	path('transaction/formset', transaction_formset_view, name = 'transaction-formset'),
	path('contract/create', ContractCreateNewView.as_view(), name = 'contract-create'),
	path('contract/list', ContractListView.as_view(), name = 'contract-list'),
	path('contract/detail/<int:pk>/', ContractDetailView.as_view(), name = 'contract-detail'),
	path('contract/update/<int:pk>/', ContractUpdateView.as_view(), name = 'contract-update'),
	path('contract/formset', contract_formset_view, name = 'transaction-formset'),
]

my_app/models.py
from django.db import models
from django.db.models import Sum
from django.core.validators import MinValueValidator
from decimal import Decimal
from website.settings import DATE_INPUT_FORMATS


class Region(models.Model):
	name = models.CharField(max_length=30, default='')

	def __str__(self):
		return self.name


class Building(models.Model):
	epims_id = models.CharField('ePIMS ID', max_length=50)
	name = models.CharField('Name', max_length=50)
	region = models.ForeignKey(Region, on_delete=models.CASCADE, default='')
	nia = models.DecimalField('NIA', decimal_places=2, max_digits=20, default=0)
	ftes_capacity = models.DecimalField('FTEs Capacity', decimal_places=2,
										max_digits=20, default=0)
	image = models.ImageField(default='images/default.png', upload_to='images')
	cost_centre = models.CharField('Cost Centre', max_length=50, default='')

	def __str__(self):
		return self.name


class CostType(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'Cost Types'


class Cost(models.Model):
	start = models.DateField()
	end = models.DateField()
	cost_type = models.ForeignKey(CostType, on_delete=models.CASCADE, default='')
	building = models.ForeignKey(Building, on_delete=models.CASCADE, default='')
	option = models.IntegerField()
	value = models.DecimalField(decimal_places=2, max_digits=20, default=0)

	def __str__(self):
		return str(self.cost_type) + ':' + str(self.start)


class AccountType(models.Model):
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'Account Types'


class Hierarchy1(models.Model):
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name


class Hierarchy2(models.Model):
	hierarchy1 = models.ForeignKey(Hierarchy1, on_delete=models.CASCADE,
								   default='')
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name


class Hierarchy3(models.Model):
	hierarchy2 = models.ForeignKey(Hierarchy2, on_delete=models.CASCADE,
								   default='')
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name


class Hierarchy4(models.Model):
	hierarchy3 = models.ForeignKey(Hierarchy3, on_delete=models.CASCADE,
								   default='')
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name


class Account(models.Model):
	number = models.IntegerField()
	account_type = models.ForeignKey(AccountType, on_delete=models.CASCADE)
	hierarchy4 = models.ForeignKey(Hierarchy4, on_delete=models.CASCADE)
	description = models.CharField(max_length=50, default='')
	is_live = models.BooleanField('Live', default=True)

	class Meta:
		ordering = ('description',)

	def __str__(self):
		return self.description


class Direction(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name


class AbstractEntry(models.Model):
	direction = models.ForeignKey(Direction, on_delete=models.CASCADE,
								  default='')
	account = models.ForeignKey(Account, on_delete=models.CASCADE, default='')
	amount = models.DecimalField(decimal_places=2, max_digits=20, default=0,
								 validators=[MinValueValidator(Decimal('0.00'))])

	def __str__(self):
		return str(self.direction)+':'+str(self.account)+':'+str(self.amount)

	class Meta:
		abstract = True
		verbose_name_plural = 'Abstract Entries'


class TransactionGroup(models.Model):
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name

		class Meta:
			verbose_name_plural = 'Entry Groups'


class TransactionType(models.Model):
	name = models.CharField(max_length=50, default='')
	group = models.ForeignKey(TransactionGroup, on_delete=models.CASCADE,
							  default='', null=True, blank=True,
							  verbose_name='Transaction Group')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'Transaction Types'


class PseudoEntry(AbstractEntry):
	transaction_type = models.ForeignKey(TransactionType,
										 on_delete=models.CASCADE, default='',
										 verbose_name='Transaction Type')
	amount = models.DecimalField(decimal_places=2, max_digits=20, default=0)

	def __str__(self):
		return str(self.transaction_type.name)
		+' / '
		+str(self.direction)
		+':'+str(self.account)

	class Meta:
		verbose_name_plural = 'Pseudo Entries'


class OrganisationType(models.Model):
	name = models.CharField(max_length=50)

	class Meta:
		verbose_name_plural = 'Organisation Types'


class Organisation(models.Model):
	name = models.CharField(max_length=50)
	organisation_type = models.ForeignKey(OrganisationType,
										  on_delete=models.CASCADE, null=True,
										  blank=True)
	reference = models.IntegerField()
	sort_code = models.IntegerField()
	account_number = models.IntegerField()
	postcode = models.CharField(max_length=50, default='')
	address = models.TextField(max_length=200, default='')

	def __str__(self):
		return self.name


class AssetType(models.Model):
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'Asset Types'


class ProfitCentre(models.Model):
	name = models.IntegerField()

	def __str__(self):
		return str(self.name)

	class Meta:
		verbose_name_plural = 'Profit Centres'


class ContractType(models.Model):
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'Contract Types'


class Contract(models.Model):
	REVENUE_EXPENDITURE = (('R', 'Revenue'), ('E', 'Expenditure'))
	TREATMENT = (('Lessee', 'Lessee'), ('Lessor', 'Lessor'))
	description = models.CharField(max_length=50)
	revenue_expenditure = models.CharField(
		'Revenue/Expenditure', max_length=50, choices=REVENUE_EXPENDITURE)
	contract_type = models.ForeignKey(ContractType, on_delete=models.CASCADE,
									  null=True, blank=True,
									  verbose_name='Contract Type')
	organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE,
									 null=True, blank=True,
									 verbose_name='Counterparty')
	building = models.ManyToManyField(Building, blank=True)
	treatment = models.CharField('Treatment', max_length=50, null=True,
								 blank=True, choices=TREATMENT)
	start = models.DateField(null=True, blank=True)
	end = models.DateField(null=True, blank=True)
	signed = models.BooleanField(default=False)

	class Meta:
		ordering = ('-id',)

	def __str__(self):
		if self.contract_type:
			return self.contract_type.name+':'+self.description+' ['
			+str(self.start_date)+' to '+str(self.end_date)+' ]'
		else:
			return self.description+' ['+str(self.start_date)+' to '
			+str(self.end_date)+' ]'

	@property
	def npv(self):
		record = self.transaction_set.get(
			transaction_type__name='Recognise Lease')
		npv = record.amount
		return npv

	@property
	def total_payments(self):
		qs = self.contractpayment_set.all()
		total_payments = qs.aggregate(Sum('amount'))['amount__sum']
		return total_payments

	@property
	def total_interest(self):
		qs = self.transaction_set.filter(transaction_type__name='Pay Interest')
		total_interest = qs.aggregate(Sum('amount'))['amount__sum']
		return total_interest

	@property
	def start_date(self):
		qs = self.transaction_set.order_by('date')
		try:
			start_date = qs.first().date
			return start_date
		except:
			return

	@property
	def end_date(self):
		qs = self.transaction_set.order_by('date')
		try:
			end_date = qs.last().date
			return end_date
		except:
			return


class Transaction(models.Model):
	TREATMENT = (('Accounting', 'Accounting'), ('Budgeting', 'Budgeting'))
	ACTUAL_EXPECTED = (('E', 'Expected'), ('A', 'Actual'))
	date = models.DateField()
	transaction_type = models.ForeignKey(TransactionType,
										 on_delete=models.CASCADE, null=True,
										 blank=True,
										 verbose_name='Transaction Type')
	comment = models.TextField(max_length=200, default='', null=True,
													   blank=True)
	contract = models.ForeignKey(Contract, on_delete=models.CASCADE, null=True,
								 blank=True)
	actual_expected = models.CharField('Actual/Expected', max_length=50,
									   choices=ACTUAL_EXPECTED, default='E')
	period = models.CharField(max_length=50, null=True, blank=True)
	amount = models.DecimalField(decimal_places=2, max_digits=20, default=0,
								 null=True,
								 validators=[MinValueValidator(Decimal('0.01'))])
	treatment = models.CharField('Treatment', max_length=50, choices=TREATMENT,
								 null=True, blank=True, default='')
	time_index = models.IntegerField(null=True, blank=True, default=0)

	def __str__(self):
		return str(self.transaction_type) + ':' + str(self.date)


class ContractPayment(models.Model):
	TREATMENT = (('Accounting', 'Accounting'), ('Budgeting', 'Budgeting'))
	ACTUAL_EXPECTED = (('E', 'Expected'), ('A', 'Actual'))
	date = models.DateField(null=True, blank=True)
	transaction_type = models.ForeignKey(TransactionType,
										 on_delete=models.CASCADE, null=True,
										 blank=True,
										 verbose_name='Transaction Type')
	comment = models.TextField(max_length=200, default='', null=True, blank=True)
	contract = models.ForeignKey(Contract, on_delete=models.CASCADE, null=True,
								 blank=True)
	actual_expected = models.CharField('Actual/Expected', max_length=50,
									   choices=ACTUAL_EXPECTED, default='E')
	period = models.CharField(max_length=50, null=True, blank=True)
	amount = models.DecimalField(decimal_places=2, max_digits=20, default=0,
								 null=True,
								 validators=[MinValueValidator(Decimal('0.01'))])
	treatment = models.CharField('Treatment', max_length=50, choices=TREATMENT,
								 null=True, blank=True, default='')
	time_index = models.IntegerField(null=True, blank=True, default=0)

	def __str__(self):
		return str(self.transaction_type) + ':' + str(self.date)


class Entry(AbstractEntry):

my_app/templates/my_app/contract/contract-create.html
{% extends 'basic/base.html' %}
{% block content %}
{% load static %}
<h2>
	Create Contract&nbsp;
	<a type='button' class="btn btn-light" href='' >
		<i class="fas fa-undo-alt"></i>
	</a>
</h2>
	<div class="input-group mb-3">
		<div class="input-group-prepend">
			<label class="input-group-text">Amount</label>
			<span class="input-group-text"><i class="fas fa-pound-sign"></i></span>
		</div>
		<input class="form-control" type="number" min="0.00" step="0.01" name='amount' id='id_amount' oninput="this.value =
 !!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null"></input>
		<div class="input-group-append">
			<button type='button' class="btn btn-outline-secondary" id='resetBtnAmount'><i class="fas fa-undo-alt"></i></button>
		</div>
		<div class="input-group-prepend">
			<label class="input-group-text">Frequency</label>
			<span class="input-group-text"><i class="fas fa-clock"></i></span>
		</div>
		<select class="form-control" type="number" name='Frequency' id='id_frequency'>
			<option value="1">Annually</option>
		</select>
		<div class="input-group-append">
			<button type='button' class="btn btn-outline-secondary" id='resetBtnAmount'><i class="fas fa-undo-alt"></i></button>
		</div>
	</div>
<hr>
<form class='form-horizontal' method='POST' enctype="multipart/form-data" novalidate>
	{% csrf_token %}
	<fieldset>
		{% for field in form %}
			<div class="row">
				<div class='col col-2'>
					<p class='text-muted'>{{ field.label }}</p>
				</div>
				<div class='col col-6'>
					{{ field }}
				</div>
				<div class='col'>
					{% if field.errors %}
						{% for error in field.errors %}
							<p class='text-danger'>{{ error | safe }}</p>
						{% endfor %}
					{% endif %}
				</div>
			</div>
		{% endfor %}
	</fieldset>
	<hr class='my-4'>
	<h4>Expected Payments</h4>
	<h5>
		<span class='text-muted'>from</span>
		<span id='start-date'>start date</span>
		<span class='text-muted'>to</span>
		<span id='end-date'>end date</span>
	</h5>
	<div id='formset'>
		{% include 'my_app/contract/contract-formset.html' %}
	</div>
	<a class='btn btn-outline-info mt-2' id='btn-add' href='#'>Add Expected Payment&nbsp;<i class="fas fa-plus"></i></a>
	<div class='row mt-4'>
		<button class="btn btn-outline-success ml-2" type="submit">
			Create <i class="far fa-edit"></i>
		</button>
	</div>
</form>
{% endblock content %}

{% block js %}

<script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js'></script>
<!-- <script src='{% static 'my_app/js/reset.js' %}'></script> -->

<script src='{% static 'my_app/js/datepicker.js' %}'></script>
<script src='{% static 'my_app/js/renderFormset2.js' %}'></script>
<script type="text/javascript">
	var endpoint = '/contract/formset';
</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

{% endblock %}

my_app/templates/my_app/contract/contract-detail.html
{% extends 'basic/base.html' %}
{% block content %}
{% load static %}
{% load humanize %}
<input type='hidden' id='id' value={{id}}></input>
<div class='container mb-2 p-0'>
	<div class='row justify-content-start'>
		<div class='col-auto'>
			<h1>{{ record.contract_type }}</h1>
		</div>
		<div class='col-auto align-self-center p-0'>
			<a class="btn btn-outline-info align-self-center" href='{% url 'contract-update' record.id %}' role="button">Update&nbsp;<i class="far fa-edit"></i></a>
		</div>
	</div>
</div>
<div class="card mb-3 shadow-sm" style="">
	<div class="card-body">
		<div class='container'>
			<div class='row'>
				<div class='col'>
					<h5 class="font-weight-light">{{ record.get_revenue_expenditure_display }}</h5>
					<p><span class='text-muted'>from&nbsp;</span><span>{{ record.start_date }}</span><span class='text-muted'>&nbsp;to&nbsp;</span><span>{{ record.end_date }}</span><p>
					{% if record.building.all %}
					<h6>Building{% if record.building.count > 1 %}s <span class='text-muted'>({{record.building.count}})</span>{% endif %}</h6>
						{% for building in record.building.all %}
								<a href='{% url 'building-detail' building.id %}'><h6>{{ building.name }}</h6></a>
						{% endfor %}
					{% endif %}

				</div>
				<div class='col'>
					<h5><span class='font-weight-light'>Total Payments</span>&nbsp;£{{record.total_payments|floatformat:2|intcomma }}</h5>
					<hr>
					<h5><span class='font-weight-light'>Recognised Asset</span>&nbsp;£{{record.npv|floatformat:2|intcomma }}</h5>
					<h5><span class='font-weight-light'>Interest Payments</span>&nbsp;£{{record.total_interest|floatformat:2|intcomma }}</h5>
				</div>
			</div>
			<div class='row'>
				<div class='col'>
					<h6>Description&nbsp;</h6>
					<p class='text-muted'>{{ record.description }}</p>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="list-group mb-4">
	{% for payment in record.contractpayment_set.all %}
				<div class='container list-group-item'>
					<div class='row'>
						<div class='col'>
							{{ payment.date }}
						</div>
						<div class='col'>
							{{ payment.get_actual_expected_display }}
						</div>
						<div class='col'>
							<h5><span class="badge badge-info badge">£{{payment.amount|floatformat:2|intcomma }}</span><h5>
						</div>
						<div class='col border-left'>
							{% if not payment.receivedinvoice_set.all and not payment.issuedinvoice_set.all %}
								<a href='{% url "invoice-create" pk=payment.pk %}?next={{ request.path|urlencode }}' class='btn btn-block btn-light'>Create Invoice&nbsp;<i class="far fa-edit"></i></a>
							{% else %}
								<a href='#' class='btn btn-block btn-light'>Update Invoice&nbsp;<i class="far fa-edit"></i></a>
							{% endif %}
						</div>
						<div class='col'>
							{% if payment.receivedinvoice_set.first.pdf.url %}
								<a href='{{ payment.receivedinvoice_set.first.pdf.url }}' class='btn btn-block btn-light'>PDF File&nbsp;<i class="far fa-file-pdf"></i></a>
							{% endif %}
							{% if payment.issuedinvoice_set.first.pdf.url %}
								<a href='{{ payment.issuedinvoice_set.first.pdf.url }}' class='btn btn-block btn-light'>PDF File&nbsp;<i class="far fa-file-pdf"></i></a>
							{% endif %}
						</div>
					</div>
				</div>
	{% endfor %}
</div>
	<h3>Accounting</h3>
	<h6 class='text-muted'>IFRS16</h6>
	{% regroup record.transaction_set.all by time_index as accounting_list %}
	{% for time_index,transactions in accounting_list %}
		<div class="list-group mb-4">
		{% for transaction in transactions %}
			{% if transaction.treatment %}
				<div class='container list-group-item p-2'>
					<div class='row'>
						<div class='col'>
							{{ transaction.date }}
						</div>
						<div class='col'>
							{{ transaction.transaction_type }}
						</div>
						<div class='col'>
							{{ transaction.get_actual_expected_display }}
						</div>
						<div class='col'>
							<h5><span class="badge badge-info badge">£{{transaction.amount|floatformat:2|intcomma }}</span><h5>
						</div>
					</div>
				</div>
			{% endif %}
		{% endfor %}
	</div>
	{% endfor %}
</div>
<div class='container'>
	<div class='row justify-content-center' id='spinner'>
		<div class="mt-4 spinner-border text-info" role="status" >
			<span class="sr-only">Loading...</span>
		</div>
	</div>
	<div class='row'>
		<canvas id="myLine"></canvas>
	</div>
	<div class='row text-muted text-right' id='source' style='display:none;'>
		<small><b>Lease Liablility&nbsp;</b>IFRS16</small>
		<hr>
	</div>
</div>
{% endblock content %}

{% block js %}
	<script src='{% static 'my_app/js/liability.js' %}'></script>
{% endblock %}

my_app/templates/my_app/contract/contract-list.html
{% extends 'basic/base.html' %}
{% block content %}
{% load static %}
{% load humanize %}
<div class='container mb-2 p-0'>
	<div class='row justify-content-start'>
		<div class='col-auto'>
			<h1>Contracts</h1>
		</div>
		<div class='col-auto align-self-center p-0'>
			<a class="btn btn-outline-success align-self-center" href='{% url 'contract-create' %}' role="button">Create&nbsp;<i class="far fa-edit"></i></a>
		</div>
	</div>
</div>
{% include 'my_app/contract/contract-filter.html' %}
<hr>

	{% for record in qs %}
		<div class="card mb-3 shadow" style="">
			<div class="card-header py-2">
				<div class='flex-container'>
					<div class='row align-items-center justify-content-between'>
						<div class='col-auto align-self-center'>
							<a href='{% url 'contract-detail' record.id %}'><h4 class='d-inline'>{{ record.contract_type }}</h4></a>
						</div>
						<div class='col pl-0'>
							<a href="#" class="badge badge-info">{{ record.organisation }}</a>
						</div>
						<div class='col col-auto text-right'>
							<a href='{% url 'contract-update' record.id %}' class="btn btn-sm btn-outline-info border-0" role="button" aria-disabled="true">
								<i class='far fa-edit'></i>
							</a>
						</div>
					</div>
				</div>
			</div>
			<div class="card-body">
				<div class='container'>
					<div class='row'>
						<div class='col'>
							<h5 class="font-weight-light">{{ record.get_revenue_expenditure_display }}</h5>
							<p><span class='text-muted'>from&nbsp;</span><span>{{ record.start_date }}</span><span class='text-muted'>&nbsp;to&nbsp;</span><span>{{ record.end_date }}</span><p>
							{% if record.building.all %}
							<h6>Building{% if record.building.count > 1 %}s <span class='text-muted'>({{record.building.count}})</span>{% endif %}</h6>
								{% for building in record.building.all %}
										<a href='{% url 'building-detail' building.id %}'><h6>{{ building.name }}</h6></a>
								{% endfor %}
							{% endif %}

						</div>
						<div class='col'>
							<h5><span class='font-weight-light'>Total Payments</span>&nbsp;£{{record.total_payments|floatformat:2|intcomma }}</h5>
							<hr>
							<h5><span class='font-weight-light'>Recognised Asset</span>&nbsp;£{{record.npv|floatformat:2|intcomma }}</h5>
							<h5><span class='font-weight-light'>Interest Payments</span>&nbsp;£{{record.total_interest|floatformat:2|intcomma }}</h5>
						</div>
					</div>
					<div class='row'>
						<div class='col'>
							<a class="btn-sm btn-secondary my-2" data-toggle="collapse" href="#collapse-{{record.id}}" role="button" aria-expanded="false" aria-controls="collapse-{{record.id}}">
								Details
							</a>
							<ul class="list-group collapse mt-2" id="collapse-{{record.id}}">
									<li class="list-group-item">
										<p>Description&nbsp;</p>
										<p class='text-muted'>{{ record.description }}</p>
									</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	{% endfor %}

{% endblock content %}

{% block js %}
	<script src='{% static 'my_app/js/datepicker.js' %}'></script>
	<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js'></script>
	<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css'/>

	<script src='{% static 'my_app/js/reset.js' %}'></script>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

	<!-- (Optional) Latest compiled and minified JavaScript translation files -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/i18n/defaults-*.min.js"></script>
{% endblock %}

my_app/templates/my_app/contract/contract-update.html
{% extends 'basic/base.html' %}
{% block content %}
{% load static %}
<h2>
	Update Contract&nbsp;
	<a type='button' class="btn btn-light" href='' >
		<i class="fas fa-undo-alt"></i>
	</a>
</h2>
	<div class="input-group mb-3">
		<div class="input-group-prepend">
			<label class="input-group-text">Amount</label>
			<span class="input-group-text"><i class="fas fa-pound-sign"></i></span>
		</div>
		<input class="form-control" type="number" min="0.00" step="0.01" name='amount' id='id_amount' oninput="this.value =
 !!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null"></input>
		<div class="input-group-append">
			<button type='button' class="btn btn-outline-secondary" id='resetBtnAmount'><i class="fas fa-undo-alt"></i></button>
		</div>
		<div class="input-group-prepend">
			<label class="input-group-text">Frequency</label>
			<span class="input-group-text"><i class="fas fa-clock"></i></span>
		</div>
		<select class="form-control" type="number" name='Frequency' id='id_frequency'>
			<option value="1">Annually</option>
			<option value="2">Quarterly</option>
			<option value="3">Monthly</option>
		</select>
		<div class="input-group-append">
			<button type='button' class="btn btn-outline-secondary" id='resetBtnAmount'><i class="fas fa-undo-alt"></i></button>
		</div>
	</div>
<hr>
<form class='form-horizontal' method='POST' enctype="multipart/form-data" novalidate>
	{% csrf_token %}
	<fieldset>
		{% for field in form %}
			<div class="row">
				<div class='col col-2'>
					<p class='text-muted'>{{ field.label }}</p>
				</div>
				<div class='col col-6'>
					{{ field }}
				</div>
				<div class='col'>
					{% if field.errors %}
						{% for error in field.errors %}
							<p class='text-danger'>{{ error | safe }}</p>
						{% endfor %}
					{% endif %}
				</div>
			</div>
		{% endfor %}
	</fieldset>
	<hr class='my-4'>
	<h4>Expected Payments</h4>
	<h5>
		<span class='text-muted'>from</span>
		<span id='start-date'>start date</span>
		<span class='text-muted'>to</span>
		<span id='end-date'>end date</span>
	</h5>
	<div id='formset'>
		{% include 'my_app/contract/contract-formset.html' %}
	</div>
	<a class='btn btn-outline-info mt-2' id='btn-add' href='#'>Add Expected Payment&nbsp;<i class="fas fa-plus"></i></a>
	<div class='row mt-4'>
		<button class="btn btn-outline-success ml-2" type="submit">
			Update&nbsp;<i class="far fa-edit"></i>
		</button>
	</div>
</form>
{% endblock content %}

{% block js %}

<script src='{% static 'my_app/js/formset.js' %}'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js'></script>
<!-- <script src='{% static 'my_app/js/reset.js' %}'></script> -->

<script src='{% static 'my_app/js/datepicker.js' %}'></script>
<script src='{% static 'my_app/js/renderFormset2.js' %}'></script>
<script type="text/javascript">
	var endpoint = '/contract/formset';
</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

{% endblock %}