my_app/urls.py
from django.urls import path
from my_app.views import *


urlpatterns = [
	path('building/create/', BuildingCreateView.as_view(), name = 'building-create'),
	path('building/list/', BuildingListView.as_view(), name = 'building-list'),
	path('building/detail/<int:pk>/', BuildingDetailView.as_view(), name = 'building-detail'),
	path('building/update/<int:pk>/', BuildingUpdateView.as_view(), name = 'building-update'),
	path('building/delete/<int:pk>/', BuildingDeleteView.as_view(), name = 'building-delete'),
	path('transaction/create', TransactionCreateView.as_view(), name = 'transaction-create'),
	path('transaction/list', TransactionListView.as_view(), name = 'transaction-list'),
	path('transaction/update/<int:pk>/', TransactionUpdateView.as_view(), name = 'transaction-update'),
	path('transaction/formset', transaction_formset_view, name = 'transaction-formset'),
	path('contract/create', ContractCreateNewView.as_view(), name = 'contract-create'),
	path('contract/list', ContractListView.as_view(), name = 'contract-list'),
	path('contract/detail/<int:pk>/', ContractDetailView.as_view(), name = 'contract-detail'),
	path('contract/update/<int:pk>/', ContractUpdateView.as_view(), name = 'contract-update'),
	path('contract/formset', contract_formset_view, name = 'transaction-formset'),
]

my_app/models.py
from django.db import models
from django.db.models import Sum
from django.core.validators import MinValueValidator
from decimal import Decimal
from website.settings import DATE_INPUT_FORMATS


class Region(models.Model):
	name = models.CharField(max_length=30, default='')

	def __str__(self):
		return self.name


class Building(models.Model):
	epims_id = models.CharField('ePIMS ID', max_length=50)
	name = models.CharField('Name', max_length=50)
	region = models.ForeignKey(Region, on_delete=models.CASCADE, default='')
	nia = models.DecimalField('NIA', decimal_places=2, max_digits=20, default=0)
	ftes_capacity = models.DecimalField('FTEs Capacity', decimal_places=2,
										max_digits=20, default=0)
	image = models.ImageField(default='images/default.png', upload_to='images')
	cost_centre = models.CharField('Cost Centre', max_length=50, default='')

	def __str__(self):
		return self.name


class CostType(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'Cost Types'


class Cost(models.Model):
	start = models.DateField()
	end = models.DateField()
	cost_type = models.ForeignKey(CostType, on_delete=models.CASCADE, default='')
	building = models.ForeignKey(Building, on_delete=models.CASCADE, default='')
	option = models.IntegerField()
	value = models.DecimalField(decimal_places=2, max_digits=20, default=0)

	def __str__(self):
		return str(self.cost_type) + ':' + str(self.start)


class AccountType(models.Model):
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'Account Types'


class Hierarchy1(models.Model):
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name


class Hierarchy2(models.Model):
	hierarchy1 = models.ForeignKey(Hierarchy1, on_delete=models.CASCADE,
								   default='')
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name


class Hierarchy3(models.Model):
	hierarchy2 = models.ForeignKey(Hierarchy2, on_delete=models.CASCADE,
								   default='')
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name


class Hierarchy4(models.Model):
	hierarchy3 = models.ForeignKey(Hierarchy3, on_delete=models.CASCADE,
								   default='')
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name


class Account(models.Model):
	number = models.IntegerField()
	account_type = models.ForeignKey(AccountType, on_delete=models.CASCADE)
	hierarchy4 = models.ForeignKey(Hierarchy4, on_delete=models.CASCADE)
	description = models.CharField(max_length=50, default='')
	is_live = models.BooleanField('Live', default=True)

	class Meta:
		ordering = ('description',)

	def __str__(self):
		return self.description


class Direction(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name


class AbstractEntry(models.Model):
	direction = models.ForeignKey(Direction, on_delete=models.CASCADE,
								  default='')
	account = models.ForeignKey(Account, on_delete=models.CASCADE, default='')
	amount = models.DecimalField(decimal_places=2, max_digits=20, default=0,
								 validators=[MinValueValidator(Decimal('0.00'))])

	def __str__(self):
		return str(self.direction)+':'+str(self.account)+':'+str(self.amount)

	class Meta:
		abstract = True
		verbose_name_plural = 'Abstract Entries'


class TransactionGroup(models.Model):
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name

		class Meta:
			verbose_name_plural = 'Entry Groups'


class TransactionType(models.Model):
	name = models.CharField(max_length=50, default='')
	group = models.ForeignKey(TransactionGroup, on_delete=models.CASCADE,
							  default='', null=True, blank=True,
							  verbose_name='Transaction Group')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'Transaction Types'


class PseudoEntry(AbstractEntry):
	transaction_type = models.ForeignKey(TransactionType,
										 on_delete=models.CASCADE, default='',
										 verbose_name='Transaction Type')
	amount = models.DecimalField(decimal_places=2, max_digits=20, default=0)

	def __str__(self):
		return str(self.transaction_type.name)
		+' / '
		+str(self.direction)
		+':'+str(self.account)

	class Meta:
		verbose_name_plural = 'Pseudo Entries'


class OrganisationType(models.Model):
	name = models.CharField(max_length=50)

	class Meta:
		verbose_name_plural = 'Organisation Types'


class Organisation(models.Model):
	name = models.CharField(max_length=50)
	organisation_type = models.ForeignKey(OrganisationType,
										  on_delete=models.CASCADE, null=True,
										  blank=True)
	reference = models.IntegerField()
	sort_code = models.IntegerField()
	account_number = models.IntegerField()
	postcode = models.CharField(max_length=50, default='')
	address = models.TextField(max_length=200, default='')

	def __str__(self):
		return self.name


class AssetType(models.Model):
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'Asset Types'


class ProfitCentre(models.Model):
	name = models.IntegerField()

	def __str__(self):
		return str(self.name)

	class Meta:
		verbose_name_plural = 'Profit Centres'


class ContractType(models.Model):
	name = models.CharField(max_length=50, default='')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'Contract Types'


class Contract(models.Model):
	REVENUE_EXPENDITURE = (('R', 'Revenue'), ('E', 'Expenditure'))
	TREATMENT = (('Lessee', 'Lessee'), ('Lessor', 'Lessor'))
	description = models.CharField(max_length=50)
	revenue_expenditure = models.CharField(
		'Revenue/Expenditure', max_length=50, choices=REVENUE_EXPENDITURE)
	contract_type = models.ForeignKey(ContractType, on_delete=models.CASCADE,
									  null=True, blank=True,
									  verbose_name='Contract Type')
	organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE,
									 null=True, blank=True,
									 verbose_name='Counterparty')
	building = models.ManyToManyField(Building, blank=True)
	treatment = models.CharField('Treatment', max_length=50, null=True,
								 blank=True, choices=TREATMENT)
	start = models.DateField(null=True, blank=True)
	end = models.DateField(null=True, blank=True)
	signed = models.BooleanField(default=False)

	class Meta:
		ordering = ('-id',)

	def __str__(self):
		if self.contract_type:
			return self.contract_type.name+':'+self.description+' ['
			+str(self.start_date)+' to '+str(self.end_date)+' ]'
		else:
			return self.description+' ['+str(self.start_date)+' to '
			+str(self.end_date)+' ]'

	@property
	def npv(self):
		record = self.transaction_set.get(
			transaction_type__name='Recognise Lease')
		npv = record.amount
		return npv

	@property
	def total_payments(self):
		qs = self.contractpayment_set.all()
		total_payments = qs.aggregate(Sum('amount'))['amount__sum']
		return total_payments

	@property
	def total_interest(self):
		qs = self.transaction_set.filter(transaction_type__name='Pay Interest')
		total_interest = qs.aggregate(Sum('amount'))['amount__sum']
		return total_interest

	@property
	def start_date(self):
		qs = self.transaction_set.order_by('date')
		try:
			start_date = qs.first().date
			return start_date
		except:
			return

	@property
	def end_date(self):
		qs = self.transaction_set.order_by('date')
		try:
			end_date = qs.last().date
			return end_date
		except:
			return


class Transaction(models.Model):
	TREATMENT = (('Accounting', 'Accounting'), ('Budgeting', 'Budgeting'))
	ACTUAL_EXPECTED = (('E', 'Expected'), ('A', 'Actual'))
	date = models.DateField()
	transaction_type = models.ForeignKey(TransactionType,
										 on_delete=models.CASCADE, null=True,
										 blank=True,
										 verbose_name='Transaction Type')
	comment = models.TextField(max_length=200, default='', null=True,
													   blank=True)
	contract = models.ForeignKey(Contract, on_delete=models.CASCADE, null=True,
								 blank=True)
	actual_expected = models.CharField('Actual/Expected', max_length=50,
									   choices=ACTUAL_EXPECTED, default='E')
	period = models.CharField(max_length=50, null=True, blank=True)
	amount = models.DecimalField(decimal_places=2, max_digits=20, default=0,
								 null=True,
								 validators=[MinValueValidator(Decimal('0.01'))])
	treatment = models.CharField('Treatment', max_length=50, choices=TREATMENT,
								 null=True, blank=True, default='')
	time_index = models.IntegerField(null=True, blank=True, default=0)

	def __str__(self):
		return str(self.transaction_type) + ':' + str(self.date)


class ContractPayment(models.Model):
	TREATMENT = (('Accounting', 'Accounting'), ('Budgeting', 'Budgeting'))
	ACTUAL_EXPECTED = (('E', 'Expected'), ('A', 'Actual'))
	date = models.DateField(null=True, blank=True)
	transaction_type = models.ForeignKey(TransactionType,
										 on_delete=models.CASCADE, null=True,
										 blank=True,
										 verbose_name='Transaction Type')
	comment = models.TextField(max_length=200, default='', null=True, blank=True)
	contract = models.ForeignKey(Contract, on_delete=models.CASCADE, null=True,
								 blank=True)
	actual_expected = models.CharField('Actual/Expected', max_length=50,
									   choices=ACTUAL_EXPECTED, default='E')
	period = models.CharField(max_length=50, null=True, blank=True)
	amount = models.DecimalField(decimal_places=2, max_digits=20, default=0,
								 null=True,
								 validators=[MinValueValidator(Decimal('0.01'))])
	treatment = models.CharField('Treatment', max_length=50, choices=TREATMENT,
								 null=True, blank=True, default='')
	time_index = models.IntegerField(null=True, blank=True, default=0)

	def __str__(self):
		return str(self.transaction_type) + ':' + str(self.date)


class Entry(AbstractEntry):

my_app/templates/my_app/transaction/transaction-create.html
{% extends 'basic/base.html' %}
{% block content %}
{% load static %}
<h2>
	Create Transaction&nbsp;
	<a type='button' class="btn btn-light" href="" >
		<i class="fas fa-undo-alt"></i>
	</a>
</h2>
	<div class="input-group mb-3">
		<div class="input-group-prepend">
			<label class="input-group-text">Amount</label>
			<span class="input-group-text"><i class='fas fa-pound-sign'></i></span>
		</div>
		<input class="form-control" type="number" min="0.00" step="0.01" name='amount' id='id_amount' oninput="this.value =
 !!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null">
		<div class="input-group-append">
			<button type='button' class="btn btn-outline-secondary" id='resetBtnAmount'><i class="fas fa-undo-alt"></i></button>
		</div>
	</div>
<hr>
<form class='form-horizontal' method='POST' enctype="multipart/form-data" novalidate>
	{% csrf_token %}
	<fieldset>
		{% for field in form %}
			<div class="row">
				<div class='col col-2'>
					<p class='text-muted'>{{ field.label }}</p>
				</div>
				<div class='col col-6'>
					{{ field }}
				</div>
				<div class='col'>
					{% if field.errors %}
						{% for error in field.errors %}
							<p class='text-danger'>{{ error | safe }}</p>
						{% endfor %}
					{% endif %}
				</div>
			</div>
		{% endfor %}
	</fieldset>
	<hr class='my-4'>
	<div id='formset'>
		{% include 'my_app/transaction/transaction-formset.html' %}
	</div>
	<a class='btn btn-outline-info mt-2' id='btn-add' href='#'>Add Accounting Entry&nbsp;<i class="fas fa-plus"></i></a>
	<div class='row mt-4'>
		<button class="btn btn-outline-success ml-2" type="submit">
			Create&nbsp;<i class="far fa-edit"></i>
		</button>
	</div>
</form>
{% endblock content %}

{% block js %}

<!-- <script src='{% static 'my_app/js/reset.js' %}'></script> -->

<script src='{% static 'my_app/js/datepicker.js' %}'></script>
<script src='{% static 'my_app/js/renderFormset2.js' %}'></script>
<script type="text/javascript">
	var endpoint = '/transaction/formset';
</script>
<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js'></script>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css'/>

{% endblock %}

my_app/templates/my_app/transaction/transaction-formset.html
{{formset.management_form}}
<fieldset>
	{% for form in formset %}
	{% for hidden in form.hidden_fields %}
		{{ hidden }}
	{% endfor %}
	<div class="row-{{ forloop.counter0 }} formset_row-{{ formset.prefix }} mb-4">
		<div class="container mb-2">
			<div class="row">
			{% for field in form.visible_fields %}
				<div class='col'>
					{{ field }}
				</div>
			{% endfor %}
				<div class="col-1 align-self-center">
					<button class='btn btn-remove-row btn-sm btn-danger' id='{{ forloop.counter0 }}' type="button">Remove</button>
				</div>
			</div>
			<div class="row">
			{% for field in form.visible_fields %}
				<div class='col'>
					{% if field.errors %}
						{% for error in field.errors %}
							<p class='text-danger'>{{ error | safe }}</p>
						{% endfor %}
					{% endif %}
				</div>
				<div class="col-1 align-self-center">
				</div>
			{% endfor %}
			</div>
		</div>
	</div>
	{% endfor %}
</fieldset>

my_app/templates/my_app/transaction/transaction-list.html
{% extends 'basic/base.html' %}
{% block content %}
{% load static %}
{% load humanize %}
<div class='container mb-2 p-0'>
	<div class='row justify-content-start'>
		<div class='col-auto'>
			<h1>Transactions</h1>
		</div>
		<div class='col-auto align-self-center p-0'>
			<a class="btn btn-outline-success align-self-center" href='{% url 'transaction-create' %}' role="button">Create&nbsp;<i class="far fa-edit"></i></a>
		</div>
	</div>
</div>
<form method='GET'>
	<div class="input-group mb-3">
		<div class="input-group-prepend">
			<label class="input-group-text">Transaction Type</label>
		</div>
		<select class="custom-select" name='region' id='region'>
			<option value="" hidden
			{% if not region_id %}
				selected
			{% endif %}>
			All
			</option>
			{% for record in region_list %}
				<option value = {{ record.id }}	{% if region_id == record.id %}
				selected
				{% endif %}>
					{{ record.name }}
				</option>
			{% endfor %}
		</select>
		<div class="input-group-append">
			<button type='button' class="btn btn-outline-secondary" id='resetBtnRegion'><i class="fas fa-undo-alt"></i></button>
		</div>
	</div>
	<div class="input-group mb-3">
		<div class="input-group-prepend">
			<label class="input-group-text">Sort by...</label>
		</div>
		<select class="custom-select" name='sort_by' id='sort_by'>
			{% for k,v in sort_by_list.items %}
				<option value = '{{ v }}' {% if sort_by_val == v %} selected {% endif %}>
					{{ k }}
				</option>
			{% endfor %}
		</select>
		<div class="input-group-append">
			<button type='button' class="btn btn-outline-secondary" id='resetBtnSort'><i class="fas fa-undo-alt"></i></button>
		</div>
		<div class="input-group-append">
			<select class="form-select bg-light rounded-right border-secondary border-left-2 " name='sort_direction' >
				{% for k,v in sort_direction_list.items %}
					<option value = '{{ v }}' {% if sort_direction_val == v %} selected {% endif %}>
						{{ k }}
					</option>
				{% endfor %}
			</select>
		</div>
	</div>

	<button type="submit" class="btn btn-info">Filter & Sort <i class="fas fa-filter"></i></button>
	<button type="button" class="btn btn-outline-secondary" id='resetBtnAll'>Reset all <i class="fas fa-undo-alt"></i></button>
</form>
<hr>



<div class="list-group">
	{% for record in qs %}
		<a href='{% url 'transaction-update' record.id %}' class="list-group-item list-group-item-action">
			<div class='container'>
				<div class='row'>
					<div class='col'>
						<h5><span class="badge badge-info badge">£{{record.amount|floatformat:2|intcomma }}</span><h5>
					</div>
					<div class='col'>
						{{ record.date }}
					</div>
					<div class='col'>
						{{ record.contract.contract_type }}
					</div>
				</div>
			</div>
		</a>
	{% endfor %}
</div>
	{% for entry in record.entry_set.all %}
		<li class="list-group-item p-1 d-flex justify-content-between align-items-center">
			<span class='text-muted'>{{ entry.direction.name }}</span>
			{{ entry.account.description }}
			<span class="badge badge-info badge">£{{entry.amount|floatformat:2|intcomma }}</span>
		</li>
	{% endfor %}

{% endblock content %}

{% block js %}
	<script src='{% static 'my_app/js/reset.js' %}'></script>
{% endblock %}

my_app/templates/my_app/transaction/transaction-update.html
{% extends 'basic/base.html' %}
{% block content %}
{% load static %}
<h2>
	Update Transaction&nbsp;
	<a type='button' class="btn btn-light" href="" >
		<i class="fas fa-undo-alt"></i>
	</a>
</h2>
	<div class="input-group mb-3">
		<div class="input-group-prepend">
			<label class="input-group-text">Amount</label>
			<span class="input-group-text">£</span>
		</div>
		<input class="form-control" type="number" min="0.00" step="0.01" name='amount' id='id_amount' oninput="this.value =
 !!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null">
		<div class="input-group-append">
			<button type='button' class="btn btn-outline-secondary" id='resetBtnAmount'><i class="fas fa-undo-alt"></i></button>
		</div>
	</div>
<hr>
<form class='form-horizontal' method='POST' enctype="multipart/form-data" novalidate>
	{% csrf_token %}
	<input type="hidden" name="next" value="{{ request.GET.next }}">
	<fieldset>
		{% for field in form %}
			<div class="row">
				<div class='col col-2'>
					<p class='text-muted'>{{ field.label }}</p>
				</div>
				<div class='col col-6'>
					{{ field }}
				</div>
				<div class='col'>
					{% if field.errors %}
						{% for error in field.errors %}
							<p class='text-danger'>{{ error | safe }}</p>
						{% endfor %}
					{% endif %}
				</div>
			</div>
		{% endfor %}
	</fieldset>
	<hr class='my-4'>
	<div id='formset'>
		{% include 'my_app/transaction/transaction-formset.html' %}
	</div>
	<a class='btn btn-outline-info mt-2' id='btn-add' href='#'>Add Accounting Entry&nbsp;<i class="fas fa-plus"></i></a>
	<div class='row mt-4'>
		<button class="btn btn-outline-success ml-2" type="submit" method='post'>
			Update&nbsp;<i class="far fa-edit"></i>
		</button>
	</div>
</form>
{% endblock content %}

{% block js %}

<!-- <script src='{% static 'my_app/js/reset.js' %}'></script> -->

<script src='{% static 'my_app/js/datepicker.js' %}'></script>
<script src='{% static 'my_app/js/renderFormset2.js' %}'></script>
<script type="text/javascript">
	var endpoint = '/transaction/formset';
</script>
<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js'></script>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css'/>
{% endblock %}